### ISSUE TITLE
Problem when directive is used inside ngIf

### ISSUE THREAD

**Issue by mocni** [arkon/ng-click-outside#36] opened 2018-04-18 07:19 UTC
I am using your directive to hide modal on click-outside, but I am facing a problem when modal is inside *ngIf, and when I click to open modal, your directive is called and modal close at the same time, I tried to fix this with some async function, but it didn't work. I notice that your directive is not working correctly when it is using with *ngIf.

So this helped me:

`onClickedOutside(e: Event) {
    if (this.counter < 1) {
      this.counter += 1;
    } else{
      this.closeModalOnClick();
      this.counter = 0;
    }
  }`

Now basically I have to add this on 10 places when I am using your directive inside *ngIf.

**Comment by arkon** [comment] 2018-04-18 10:32
Did you try using `delayClickOutsideInit`?

**Comment by arkon** [comment] 2018-08-01 03:08
Going to close this as a dupe of #40.

**Closed as completed by arkon** 2018-08-01 03:08 UTC
Labels: bug, duplicate
